django_musa/urls.py
# Django Imports
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('musa.urls'), name='voting_system'),
    path('account/', include('allauth.urls'))
]

musa/urls.py
# Django imports
from django.urls import path

# Local relative imports
from . import views, role_redirect

# Authentication app imports
from authentication.views import (CustomLoginView, CustomSignupView,
                                  CustomLogoutView)

# User Profile app imports
from user_profile.views import (UserDashboard,
                                UserSettings,
                                UserPasswordChangeView,
                                UserDelete,
                                UserRole)

# Admin Profile app imports
from admin_profile.views import (AdminDashboard, AdminSettings,
                                 AdminPasswordChangeView,
                                 AdminRole)

# Vote Management app imports
from vote_management.views import (UserVoteCardCreation, AdminVoteCardCreation,
                                   AdminEventList, UserEventList,
                                   AllVoteCardsListView, HomePageSingleView,
                                   OfficialVoteCardsListView,
                                   CommunityVoteCardsListView,
                                   AdminVotes, UserVotes, UserSingleView,
                                   AdminVoteCardDetailView,
                                   AdminSingleView,
                                   EventApprovalDetailView,
                                   AdminApprovalList,
                                   CompletedVoteCardsListView)

urlpatterns = [
    # AUTHENTICATION
    path('login/', CustomLoginView.as_view(),
         name='account_login'),
    path('signup/', CustomSignupView.as_view(), name='account_signup'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),

    # USER
    path('user/', UserDashboard.as_view(),
         name='user_dashboard'),
    path('user/settings/', UserSettings.as_view(),
         name='user_settings'),
    path('user/password-change/', UserPasswordChangeView.as_view(),
         name='user_change'),
    path('user/delete/', UserDelete.as_view(), name='user_delete'),
    path('user/all', UserEventList.as_view(),
         name='user_all_events'),
    path('user/role', UserRole.as_view(),
         name='user_role'),
    path('user/votes/', UserVotes.as_view(),
         name='user_votes'),
    path('user/single/<slug:slug>/', UserSingleView.as_view(),
         name='user_single'),

    # VOTE MANAGEMENT
    path('user/create', UserVoteCardCreation.as_view(),
         name='user_creation'),

    # USER SUCCESS
    path('success/', views.UserSuccess.as_view(),
         name='user_success'),

    # OFFICE
    path('office/', AdminDashboard.as_view(),
         name='admin_dashboard'),
    path('office/settings/', AdminSettings.as_view(),
         name='admin_settings'),
    path('office/password-change/', AdminPasswordChangeView.as_view(),
         name='admin_change'),
    path('office/create', AdminVoteCardCreation.as_view(),
         name='admin_creation'),
    path('office/all', AdminEventList.as_view(),
         name='admin_all_events'),
    path('office/role', AdminRole.as_view(),
         name='admin_role'),
    path('office/votes', AdminVotes.as_view(),
         name='admin_votes'),
    path('office/single/card/<slug:slug>/', AdminSingleView.as_view(),
         name='admin_single'),
    path('office/update/<slug:slug>/', AdminVoteCardDetailView.as_view(),
         name='admin_card_update'),
    path('office/all/approve/', AdminApprovalList.as_view(),
         name='admin_approval_list'),
    path('office/approval/<slug:slug>/', EventApprovalDetailView.as_view(),
         name='admin_approval'),

    # ROLE
    path('role_redirect/', role_redirect.RoleRedirectView.as_view(),
         name='role_redirect'),

    # FRONTEND
    path('', views.HomePage.as_view(),
         name='homepage'),
    path('<slug:slug>', HomePageSingleView.as_view(),
         name='card_single'),
    path('all/', AllVoteCardsListView.as_view(),
         name='see_more'),
    path('all/official/', OfficialVoteCardsListView.as_view(),
         name='see_more_official'),
    path('all/community/', CommunityVoteCardsListView.as_view(),
         name='see_more_community'),
    path('all/completed/', CompletedVoteCardsListView.as_view(),
         name='see_more_completed'),
    path('contact/', views.ContactView.as_view(),
         name='contact_form'),
    path('faq/', views.FAQView.as_view(),
         name='faq_page'),
    path('terms/', views.TermsView.as_view(),
         name='terms_page'),
    path('policy/', views.PrivacyView.as_view(),
         name='policy_page')
]

musa/models.py
# Django Imports
from django.db import models
from django.contrib.auth.models import AbstractUser

ROLES = (
    (0, 'User'),
    (1, 'Publisher'),
    (2, 'Admin')
)


class UserProfile(AbstractUser):
    """Extended user profile with custom attributes."""
    verified = models.BooleanField(default=False)
    role = models.IntegerField(choices=ROLES, default=0)
    user_card = models.ManyToManyField(
        'vote_management.VoteCard',
        through='vote_management.VoteRecord', related_name='user_cards')

    class Meta:
        ordering = ['username']

    def __str__(self):
        return self.username

vote_management/models.py
# Django Imports
from django.db import models
from django.utils import timezone

# Library Imports
from cloudinary.models import CloudinaryField

STATUS = (
    (0, 'Draft'),
    (1, 'Online'),
    (2, 'Cancelled'),
    (3, 'Completed')
)

CARD_TYPE = (
    (0, 'Community'),
    (1, 'Official')
)


class Category(models.Model):
    """Model representing a voting category, like "Best Artist"."""
    category_name = models.CharField(max_length=50, unique=True)

    class Meta:
        ordering = ['category_name']
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category_name


class VoteCard(models.Model):
    """Model representing a card where users can cast their votes."""
    title = models.CharField(max_length=33, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        'musa.UserProfile', on_delete=models.CASCADE,
        related_name="card_author")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="categories")
    mission = models.CharField(max_length=33)
    location = models.CharField(max_length=33)
    description = models.TextField(max_length=258)
    expire = models.DateField()
    event_image = CloudinaryField('image',
                                  default='placeholder')
    vote_record = models.ManyToManyField('musa.UserProfile',
                                         through='VoteRecord',
                                         related_name='user_votes', blank=True)
    candidates = models.ManyToManyField('ElectedPerson',
                                        related_name='vote_cards',
                                        blank=True)
    status = models.IntegerField(choices=STATUS, default=0)
    excerpt = models.TextField(blank=True)
    type = models.IntegerField(choices=CARD_TYPE, default=0)
    created_on = models.DateField(auto_now_add=True)

    def is_expired(self):
        expired = self.expire <= timezone.now().date()
        return expired

    def update_card(self):
        if self.is_expired() and self.status != 3:
            self.status = 3
            self.save()

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_votes(self):
        """Return the count of votes."""
        return self.vote_record.count()


class VoteRecord(models.Model):
    """Model representing the record of a single vote by a user."""
    voter = models.ForeignKey(
        'musa.UserProfile', on_delete=models.CASCADE,
        related_name="voter_record")
    vote_card = models.ForeignKey(  # consider renaming in the future
        VoteCard, on_delete=models.CASCADE, related_name="votecard_record")
    elected_person = models.ForeignKey('ElectedPerson',
                                       on_delete=models.CASCADE,
                                       related_name="elected_record")
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['timestamp']

    def __str__(self):
        return self.elected_person.name


class ElectedPerson(models.Model):
    """Model representing a person who can be elected in a vote.
    'name' can be False in the future if necessary"""
    name = models.CharField(max_length=80, unique=True)
    is_elected = models.BooleanField(default=False)
    vote_card = models.ForeignKey(  # consider renaming in the future
        VoteCard, on_delete=models.CASCADE,
        related_name="vote_candidate", blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

templates/backend/admin-dashboard/all_events.html
{% extends "backend/admin-dashboard/base.html" %}

{% block title %}
All Events - Musa
{% endblock %}

{% block content%}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid p-4 pt-0">
            <h1 class="mt-4">All Events</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">All created events in Musa's voting system</li>
            </ol>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    Admin Created Events
                </div>
                <div class="card-body">
                    <table id="datatablesSimple">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Category</th>
                                <th>Status</th>
                                <th>Location</th>
                                <th>Created On</th>
                                <th>Expire On</th>
                                <th>Instance</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Category</th>
                                <th>Status</th>
                                <th>Location</th>
                                <th>Created On</th>
                                <th>Expire On</th>
                                <th>Instance</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for event in admin_all_events.all %}
                            <tr>
                                <td>{{ event.title }}</td>
                                {% if event.author.username == request.user.username %}
                                <td>
                                    <p class="text-success my-0 py-0 fw-semibold text-center">
                                        {{ event.author }}
                                        <small><br>({{ event.author.get_role_display }})</small>
                                    </p>
                                </td>
                                {% else %}
                                <td>
                                    <p class="my-0 py-0 fw-semibold text-center">
                                        {{ event.author }}
                                        <small><br>({{ event.author.get_role_display }})</small>
                                    </p>
                                </td>
                                {% endif %}
                                <td>{{ event.category.category_name }}</td>
                                {% if event.status == 1 %}
                                <td>
                                    <p class="text-success my-0 py-0 fw-semibold">

                                        {{ event.get_status_display }}
                                    </p>
                                </td>
                                {% elif event.status == 2%}
                                <td>
                                    <p class="text-danger my-0 py-0 fw-semibold">
                                        {{ event.get_status_display }}
                                    </p>
                                </td>
                                {% elif event.status == 0 %}
                                <td>
                                    <p class="text-warning my-0 py-0 fw-semibold">
                                        {{ event.get_status_display }}
                                    </p>
                                </td>
                                {% else %}
                                <td>
                                    <p class="text-primary my-0 py-0 fw-semibold">
                                        {{ event.get_status_display }}
                                    </p>
                                </td>
                                {% endif %}
                                <td>{{ event.location }}</td>
                                <td>{{ event.created_on }}</td>
                                {% if event.expire|date:"Y-m-d" == current_date %}
                                <td>{{ event.expire }}
                                    <small class="text-warning fw-semibold">(Today)</small>
                                </td>
                                {% elif event.expire|date:"Y-m-d" < current_date %}
                                <td>{{ event.expire }}
                                    <small class="text-danger fw-semibold">(Expired)</small>
                                </td>
                                {% else %}
                                <td>{{ event.expire }}
                                    <small class="text-success fw-semibold">(Active)</small>
                                </td>
                                {% endif %}
                                <td>
                                    <a href="{% url 'admin_single' event.slug %}">View</a> |
                                    <a href="{% url 'admin_card_update' event.slug %}">Update</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>

{% endblock %}

templates/backend/admin-dashboard/index.html
{% extends "backend/admin-dashboard/base.html" %}
{% block content %}

<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid p-4 pt-0">
            <h1 class="mt-4">Admin Dashboard</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Welcome to your Admin Dashboard</li>
            </ol>
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-primary text-white mb-4">
                        <div class="card-body">Event History</div>
                        <div class="d-flex align-items-center justify-content-between">
                            <a class="stretched-link" href="{% url 'admin_all_events' %}"></a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-warning text-white mb-4">
                        <div class="card-body">Approval</div>
                        <div class="d-flex align-items-center justify-content-between">
                            <a class="stretched-link" href="{% url 'admin_approval_list' %}"></a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-success text-white mb-4">
                        <div class="card-body">User Verification (pending)</div>
                        <div class="d-flex align-items-center justify-content-between">
                            <a class="stretched-link" href="#"></a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-danger text-white mb-4">
                        <div class="card-body">Vote History</div>
                        <div class="d-flex align-items-center justify-content-between">
                            <a class="stretched-link" href="{% url 'admin_votes' %}"></a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    Event Overview
                    <small> (Admin Created)</small>
                </div>
                <div class="card-body">
                    <table id="datatablesSimple">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Category</th>
                                <th>Status</th>
                                <th>Location</th>
                                <th>Created On</th>
                                <th>Expire On</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Category</th>
                                <th>Status</th>
                                <th>Location</th>
                                <th>Created On</th>
                                <th>Expire On</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for event in admin_dashboard.card_author.all %}
                            <tr>
                                <td>{{ event.title }}</td>
                                <td>{{ event.author }}</td>
                                <td>{{ event.category.category_name }}</td>
                                <td>{{ event.get_status_display }}</td>
                                <td>{{ event.location }}</td>
                                <td>{{ event.created_on }}</td>
                                {% if event.expire|date:"Y-m-d" == current_date %}
                                <td>{{ event.expire }}
                                    <small class="text-warning fw-semibold">(Today)</small>
                                </td>
                                {% elif event.expire|date:"Y-m-d" < current_date %}
                                <td>{{ event.expire }}
                                    <small class="text-danger fw-semibold">(Expired)</small>
                                </td>
                                {% else %}
                                <td>{{ event.expire }}
                                    <small class="text-success fw-semibold">(Active)</small>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>

{% endblock content %}

templates/backend/admin-dashboard/list_approve.html
{% extends "backend/admin-dashboard/base.html" %}

{% block title %}
Pending - Musa
{% endblock %}

{% block content%}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid p-4 pt-0">
            <h1 class="mt-4">Event Approval</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Approve created events by users</li>
            </ol>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    User's Created Events
                </div>
                <div class="card-body">
                    <table id="datatablesSimple">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Category</th>
                                <th>Status</th>
                                <th>Location</th>
                                <th>Created On</th>
                                <th>Expire On</th>
                                <th>Instance</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Category</th>
                                <th>Status</th>
                                <th>Location</th>
                                <th>Created On</th>
                                <th>Expire On</th>
                                <th>Instance</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for event in admin_approval_list.all %}
                            {% if event.status == 0 %}
                            <tr>
                                <td>{{ event.title }}</td>
                                {% if event.author.username == request.user.username %}
                                <td>
                                    <p class="text-success my-0 py-0 fw-semibold text-center">
                                        {{ event.author }}
                                        <small><br>({{ event.author.get_role_display }})</small>
                                    </p>
                                </td>
                                {% else %}
                                <td>
                                    <p class="my-0 py-0 fw-semibold text-center">
                                        {{ event.author }}
                                        <small><br>({{ event.author.get_role_display }})</small>
                                    </p>
                                </td>
                                {% endif %}
                                <td>{{ event.category.category_name }}</td>
                                {% if event.status == 1 %}
                                <td>
                                    <p class="text-success my-0 py-0 fw-semibold">

                                        {{ event.get_status_display }}
                                    </p>
                                </td>
                                {% elif event.status == 2%}
                                <td>
                                    <p class="text-danger my-0 py-0 fw-semibold">
                                        {{ event.get_status_display }}
                                    </p>
                                </td>
                                {% elif event.status == 0 %}
                                <td>
                                    <p class="text-warning my-0 py-0 fw-semibold">
                                        {{ event.get_status_display }}
                                    </p>
                                </td>
                                {% else %}
                                <td>
                                    <p class="text-primary my-0 py-0 fw-semibold">
                                        {{ event.get_status_display }}
                                    </p>
                                </td>
                                {% endif %}
                                <td>{{ event.location }}</td>
                                <td>{{ event.created_on }}</td>
                                {% if event.expire|date:"Y-m-d" == current_date %}
                                <td>{{ event.expire }}
                                    <small class="text-warning fw-semibold">(Today)</small>
                                </td>
                                {% elif event.expire|date:"Y-m-d" < current_date %}
                                <td>{{ event.expire }}
                                    <small class="text-danger fw-semibold">(Expired)</small>
                                </td>
                                {% else %}
                                <td>{{ event.expire }}
                                    <small class="text-success fw-semibold">(Active)</small>
                                </td>
                                {% endif %}
                                <td>
                                    <a href="{% url 'admin_single' event.slug %}">View</a> |
                                    <a href="{% url 'admin_approval' event.slug %}">Approve</a>
                                </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>

{% endblock %}

templates/backend/admin-dashboard/single_card_admin.html
{% extends "backend/admin-dashboard/base.html" %}

{% block title %}
{{ event.title }} - Musa
{% endblock %}

{% block content %}
<!-- Page Content-->
<div class="container px-4 px-lg-0 mt-5">

    <!-- Call to Action-->
    <div class="card bg-light my-5 py-4 text-center">
        <div class="card-body">
            <p class="m-0">You are in a dedicated page for <strong>{{ event.title }}
                </strong>
            </p>
            <small>Created by: {{ event.author }} | Category: {{ event.category }}</small>
        </div>
    </div>
    <!-- Messages -->
    {% if messages %}
    <div class="alert card card-header-blue my-5 py-4 text-center text-white alert-dismissible" role="alert">
        <div class="card-body">
            {% for message in messages %}
            <p {% if message.tags %} class="{{ message.tags }} mb-0" {% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
        <button type="button" class="btn-close text-white" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    <!-- Campaign Row-->
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="text-center">
                <a class="my-0" href="{% url 'admin_all_events' %}">Return</a>
            </div>
            <hr>
            <div class="card h-100">
                {% if event.status == 1 or event.status == 3 %}
                <div class="card-header card-header-green text-center h6">{{ event.get_status_display }}</div>
                {% elif event.status == 2%}
                <div class="card-header bg-danger text-center text-white h6">{{ event.get_status_display }}</div>
                {% else %}
                <div class="card-header bg-warning text-center text-white h6">{{ event.get_status_display }}</div>
                {% endif %}
                <div class="card-header text-center h4">{{ event.get_type_display}}</div>
                <div class="card-body card-body-height pb-0">
                    <!-- Card image & Data -->
                    <div class="row mt-2">
                        <div class="col-5 d-inline-block">
                            {% if "placeholder" in event.event_image.url %}
                            <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg"
                                alt="code institute" class="img-fluid img-thumbnail rounded float-start mx-2"
                                width="200" height="200">
                            {% else %}
                            <img src="{{ event.event_image.url }}" alt="card image"
                                class="img-fluid img-thumbnail rounded float-start mx-2" width="150" height="150">
                            {% endif %}
                        </div>
                        <div class="col-7 d-inline-block">
                            <div>
                                <p class="card-title h5">{{ event.title }}</p>
                                <p class="mission my-0 fs-6"> {{ event.mission }}</p>
                                <small class="location my-0"> {{ event.location }}</small>
                            </div>
                        </div>
                    </div>
                    <!-- Card Description -->
                    <div id="description-single" class="row mt-3">
                        <div class="col">
                            <p class="my-0">
                                {{ event.description|safe }}
                            </p>
                        </div>
                    </div>
                    <!-- Candidates -->
                    <div class="row">
                        <div class="col">
                            <div class="card">
                                <div class="card-header">
                                    <h6 class="text-center mb-0">CANDIDATES</h6>
                                </div>
                                {% if user_authenticated %}
                                <div class="card-body">
                                    {% csrf_token %}
                                    {% for candidate in event.vote_candidate.all %}
                                    <label>
                                        <input type="radio" name="elected_person" value="{{ candidate.id }}">
                                        {{ candidate.name }}
                                    </label><br>
                                    {% endfor %}
                                    {% endif %}

                                </div>
                            </div>
                        </div>

                        <!-- VOTES & PROGRESS BAR -->
                        <div class="text-center my-4">
                            <span class="card d-inline-block">
                                <div class="card-body py-1 px-3 text-center">
                                    <span class="card-text">{{ event.number_of_votes }}<br> Votes</span>
                                </div>
                            </span>
                            <div class="d-inline-block px-3 progress-container">
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" style="width: {{ event.progress }}%"
                                        aria-valuenow="{{ event.progress }}" aria-valuemin="0" aria-valuemax="100">
                                        <span >{{ event.progress }}%</span>
                                    </div>
                                </div>
                            </div>
                            <small>{{ event.time_left }} days</small>
                        </div>
                    </div>
                </div>
                <a href="{% url 'card_single' event.slug %}" class="card-footer text-center fs-5">VISIT</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}